### ISSUE TITLE
Move captions

### ISSUE THREAD

**Issue by rodrigosimpliroute** [vivek-nexus/transcriptonic#10]
Move captions to a side and implement de ability of seeing them or not , would be comfortable. Just a suggestion . Thanks !

**Comment by vivek-nexus** [comment]
Thanks for the suggestion. This is a low value, high effort feature. So will consider it if more people ask for it.

**Comment by rodrigosimpliroute** [comment]
great , thanks


*Rodrigo *

**Comment by vivek-nexus** [comment]
Dimmed down the transcript opacity to 20%, so that it is less intrusive. Refer PR #11.
