### ISSUE TITLE
Add Version in the TranscripTonic window

### ISSUE THREAD

**Issue by DevRGT** [vivek-nexus/transcriptonic#16]
Hello,

Just a suggestion.

Add the version in the Main window:

![image](https://github.com/vivek-nexus/transcriptonic/assets/40140101/b6420cf0-176e-4a74-ad6e-f4c5fb46ed1f)
![2024-06-21 13_51_57-Clipboard](https://github.com/vivek-nexus/transcriptonic/assets/40140101/2bd9a9e6-abb9-4ac4-a3e7-3df394edf546)

**Comment by vivek-nexus** [comment]
Chrome extensions auto update every 5 hours, so not much value adding this.

**Comment by vivek-nexus** [comment]
This is being added in v2.3.3
