### ISSUE TITLE
Transcription too dark

### ISSUE THREAD

**Issue by DevRGT** [vivek-nexus/transcriptonic#17]
Hello

Sometimes, not always, the transcription are behind a dark filter. So difficult to read during the meeting.

![2024-06-21 14_02_14-Meet - vrg-kbid-fga](https://github.com/vivek-nexus/transcriptonic/assets/40140101/66ce2b92-d814-4290-821c-b0f4a09270a7)

**Comment by vivek-nexus** [comment]
It is intentional. It feels like a difficulty now, since you are trying to closely watch it and test. After a couple of days/weeks, you will want the transcription to happen silently and not keep drawing your attention all the time.

https://github.com/vivek-nexus/transcriptonic/issues/10
