### ISSUE TITLE
Remove links to other users repo

### ISSUE THREAD

**Issue by TychoCeltCast** [vivek-nexus/transcriptonic#18]
I would request not to use outside sources such as this repo for messages inside the extension.
https://github.com/ejnana/transcripto-status

It is unnecessary and dislike the requirement to talk to external services on a private tool.

**Comment by vivek-nexus** [comment]
"Unnecessary" is a strong and poor conclusion reached, without giving much thought on why it is included.

1. When Google Meet updates the UI, there are high chances that it causes TranscripTonic to break. TranscripTonic will have to be updated to work with the changes done by Google Meet. Chrome extension update reviews can sometimes take days and users will be left with no communication of the bug fix being in progress. The status message allows me to immediately inform users about the downtime.
2. If you check properly, I commit to that repo and it is a dedicated repo for serving status.
