### ISSUE TITLE
Transcription only stores meet chat

### ISSUE THREAD

**Issue by LeonardoZappa** [vivek-nexus/transcriptonic#24]
For some reson, my transcripts started to store only the wrtitten chat on google meets insteAd of the subtitles from the conversation. The subtitles are selected with the correct language and it was working good until this morning.

**Comment by vivek-nexus** [comment]
Thanks for notifying about this issue. Others have reported this issue as well in #23. This is due to some new changes introduced by Google Meet. This will be fixed soon and updated automatically.
