### ISSUE TITLE
Auto download 

### ISSUE THREAD

**Issue by rodrigosimpliroute** [vivek-nexus/transcriptonic#9]
Auto-download transcriptions will be a great feature.

**Comment by vivek-nexus** [comment]
Currently, transcripts auto download at the end of each meeting. Please explain what do you actually mean by "Auto download".

**Comment by rodrigosimpliroute** [comment]
it wasnt downloading , i check again and now it works. Apparently was aconflicting with one of the many puglins i was trying. This is just what i need it . Thanks!
